// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type JailerProcessInfo struct {
	_      structs.HostLayout
	PodId  uint64
	RoleId uint32
	Flags  uint8
	Pad    [3]uint8
}

// LoadJailer returns the embedded CollectionSpec for Jailer.
func LoadJailer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_JailerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Jailer: %w", err)
	}

	return spec, err
}

// LoadJailerObjects loads Jailer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*JailerObjects
//	*JailerPrograms
//	*JailerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadJailerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadJailer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// JailerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type JailerSpecs struct {
	JailerProgramSpecs
	JailerMapSpecs
	JailerVariableSpecs
}

// JailerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type JailerProgramSpecs struct {
	FileOpen  *ebpf.ProgramSpec `ebpf:"file_open"`
	TaskAlloc *ebpf.ProgramSpec `ebpf:"task_alloc"`
}

// JailerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type JailerMapSpecs struct {
	BlockedCalls       *ebpf.MapSpec `ebpf:"blocked_calls"`
	PendingEnrollments *ebpf.MapSpec `ebpf:"pending_enrollments"`
	RoleFlags          *ebpf.MapSpec `ebpf:"role_flags"`
	TaskStorage        *ebpf.MapSpec `ebpf:"task_storage"`
}

// JailerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type JailerVariableSpecs struct {
}

// JailerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadJailerObjects or ebpf.CollectionSpec.LoadAndAssign.
type JailerObjects struct {
	JailerPrograms
	JailerMaps
	JailerVariables
}

func (o *JailerObjects) Close() error {
	return _JailerClose(
		&o.JailerPrograms,
		&o.JailerMaps,
	)
}

// JailerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadJailerObjects or ebpf.CollectionSpec.LoadAndAssign.
type JailerMaps struct {
	BlockedCalls       *ebpf.Map `ebpf:"blocked_calls"`
	PendingEnrollments *ebpf.Map `ebpf:"pending_enrollments"`
	RoleFlags          *ebpf.Map `ebpf:"role_flags"`
	TaskStorage        *ebpf.Map `ebpf:"task_storage"`
}

func (m *JailerMaps) Close() error {
	return _JailerClose(
		m.BlockedCalls,
		m.PendingEnrollments,
		m.RoleFlags,
		m.TaskStorage,
	)
}

// JailerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadJailerObjects or ebpf.CollectionSpec.LoadAndAssign.
type JailerVariables struct {
}

// JailerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadJailerObjects or ebpf.CollectionSpec.LoadAndAssign.
type JailerPrograms struct {
	FileOpen  *ebpf.Program `ebpf:"file_open"`
	TaskAlloc *ebpf.Program `ebpf:"task_alloc"`
}

func (p *JailerPrograms) Close() error {
	return _JailerClose(
		p.FileOpen,
		p.TaskAlloc,
	)
}

func _JailerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed jailer_x86_bpfel.o
var _JailerBytes []byte
